hh-italian-group/h-tautau

Cuts/include/H_tautau_2016_mssm.h
Production/interface/BaseTupleProducer.h
Production/plugins/TupleProducer_eTau.cc
Production/plugins/TupleProducer_muTau.cc

Added H-tautau_mssm Production mode

---

Production/interface/TupleProducer_eTau.h
Production/plugins/TupleProducer_eTau.cc
Production/src/BaseTupleProducer.cc

Added Spring15 25ns Veto Electron Selection

Added Spring15 25ns Veto Electron Selection

---

Analysis/include/EventTuple.h

Added wjets weight in EventTuple.h

Wjets merging

---

Analysis/include/EventLoader.h
Analysis/include/EventTuple.h
Analysis/include/SummaryTuple.h

Added new seed and split variables in Summary and Event tuples accordingly to TupleSkimmer

Tuple skimmer work

---

Analysis/include/EventTuple.h
McCorrections/include/EventWeights.h
McCorrections/include/WeightingMode.h

- EventWeights.h: added TauId weight.

Added new weight branches to EventTuple.

---

Cuts/include/H_tautau_2017_baseline.h
Cuts/include/hh_bbtautau_2017.h
Production/python/Production.py
Production/python/TauID_2017.py
Production/src/BaseTupleProducer.cc
install_framework.sh

Updated install_framework.sh with ElectronRecipes and 2017 info
Implemented new recipes for Electron and Tau ID.
Started tuning selection.

Prod v4 2017

---

Analysis/include/EventInfo.h
Analysis/include/EventTuple.h
Analysis/include/SyncTupleHTT.h
Analysis/include/TupleObjects.h
Analysis/source/SyncTreeProducer.cxx
Cuts/include/Btag_2017.h
Print/config/IT_LLR_Sync.cfg
Production/src/BaseTupleProducer.cc

B tag review in EventTuple and SyncTuple

Prod v4 2017 btag review

---

Analysis/include/EventInfo.h
Analysis/include/SyncTupleHTT.h
Analysis/source/SyncTreeProducer.cxx
Cuts/include/hh_bbtautau_2017.h
Print/config/IT_LLR_Sync.cfg
Production/src/BaseTupleProducer.cc

Implementation of VBF variables at sync Tuple level

2017 - VBF variables 

---

Production/src/BaseTupleProducer.cc

It was resolved the problem of the overlapping events in one histogram because the energy scales

Improve on the creation of the selection events histograms for all the energy scales 

---

Analysis/include/AnalysisTypes.h
Analysis/include/EventTuple.h
Analysis/include/TriggerResults.h
Analysis/source/SyncTreeProducer.cxx
Production/data/triggers_2017.cfg
Production/interface/TriggerTools.h
Production/src/BaseTupleProducer.cc
Production/src/TriggerTools.cc

Jet trigger filter matching is stored in EventTuple.

Implemented VBF trigger matching.

---

Analysis/include/EventLoader.h
Analysis/include/EventTuple.h
Analysis/include/SyncTupleHTT.h
Analysis/include/TupleObjects.h
Production/interface/BaseTupleProducer.h
Production/interface/SelectionResults.h
Production/plugins/TupleProducer_eTau.cc
Production/plugins/TupleProducer_muMu.cc
Production/plugins/TupleProducer_muTau.cc
Production/plugins/TupleProducer_tauTau.cc
Production/src/BaseTupleProducer.cc

Added jet PileUp int discriminator and method PassPuId.
Added other leptons information (p4,q,type,gen_match,gen_p4) to the producers.

Prod v4 - Jet PU and other leptons

---

Analysis/include/EventInfo.h
Analysis/include/KinFitInterface.h
Analysis/include/SyncTupleHTT.h
Analysis/source/GenMatchCheck.cxx
Analysis/source/SyncTreeProducer.cxx
CMakeLists.txt
Print/config/IT_LLR_Sync.cfg
Production/src/BaseTupleProducer.cc

- Added MT2 and mkinfit variables for sync and all variables for tauES and Jet variations.
- Added good trigger list in syncTreeProducer.
- Added new VBF jet ordering and specific methods to choose the selected bjets and vbf jets pairs.
- Added BDT variables for sync.
- Removed kinfit calculation from BaseTupleProducer and added in EventInfo to rerun at SyncTuple level
- CMakeLists.txt: added kinfit dependence

Prod v4 sync and new vbf

---

Analysis/include/EventInfo.h
Analysis/include/EventLoader.h
Analysis/include/EventTuple.h
Analysis/include/SyncTupleHTT.h
Analysis/include/TupleObjects.h
Analysis/source/SyncTreeProducer.cxx
Production/interface/SelectionResults.h
Production/src/BaseTupleProducer.cc

- Reviewed fatjet branches and fixed EventLoader.
- Using EventLoader in SyncTreeProducer.

EventTuple storage review

---

Production/src/BaseTupleProducer.cc

Applied tau ES variation for met as done for different Jec sources (not using cmssw)

Prod v4 tau es met

---

Analysis/include/TupleObjects.h

add triggerFilterMatch function

Trigger filter match

---

Analysis/include/SummaryTuple.h

- Create ExpressTuple is added
- File_desc_id and spli_id are added into EVENT_EXPRESS_DATA

Added CreatExpressTuple

---

McCorrections/include/EventWeights.h
McCorrections/include/GenEventWeight.h
McCorrections/include/WeightingMode.h

- McCorrections/include/GenEventWeight.h: Created new weight for genEventWeight
- McCorrections/include/WeightingMode.h: Add new weight to WeightType
- McCorrections/include/EventWeights.h: Include new WeightType genEventWeight, for all periods

Created and applied GenEventWeight

---

Analysis/include/EventInfo.h
Analysis/src/EventInfo.cpp
McCorrections/include/TauIdWeight.h
McCorrections/src/LeptonWeights.cpp
McCorrections/src/TauIdWeight.cpp

- EventInfo.h : Modifications in the SelectJet function and to PassEcalNoiceVetoJets, to include in both the jet PU id
- EventInfo.cpp: Application in the CreateJetInfo funcion of the jet PU id to all jets. 
- TauIdWeight.h: Implementation of new method in TauIdWeight2017: tauIdForDM.
- LeptonWeights.cpp: Updates to the formula for the tau trigger sf

Chages to apply jet PU id and updates to the tau trigger sf

---

Analysis/include/TriggerResults.h
Analysis/src/TriggerResults.cpp
McCorrections/include/TauUncertainties.h
Production/data/triggers_2016.cfg
Production/data/triggers_2017.cfg
Production/interface/BaseTupleProducer.h
Production/interface/TriggerTools.h
Production/plugins/TupleProducer_eTau.cc
Production/plugins/TupleProducer_muTau.cc
Production/plugins/TupleProducer_tauTau.cc
Production/python/Production.py
Production/src/BaseTupleProducer.cc
Production/src/TriggerTools.cc
install_framework.sh

- shift for tau pt cut of 2 GeV
- implemented new TES
- implemented new MET Filters
- implemented L1 match requirements
- implemented eta in the trigger match

Implemented different features for tau pog production:

---

Analysis/include/EventInfo.h
Analysis/src/EventInfo.cpp
Core/src/TupleObjects.cpp
Print/config/IT_new_vs_old_Sync.cfg

Fixed error for getting SVfit.
Applied decayMode filter, againstEle and againstMuon for PassLegDefaultSelection

Tau pog v1 debug

---

McCorrections/src/LeptonWeights.cpp
Print/config/IT_new_vs_old_Sync.cfg

Taken into account prescaled trigger
- Print/config/IT_new_vs_old_Sync.cfg: added final_weight

Fixed trigger weight for mutau and etau 

---

Analysis/include/EventInfo.h
Analysis/include/SignalObjectSelector.h
Analysis/include/TriggerResults.h
Analysis/source/GenMatchCheck.cxx
Analysis/src/EventInfo.cpp
Analysis/src/SignalObjectSelector.cpp
Analysis/src/TriggerResults.cpp
Core/include/TupleObjects.h
Core/src/TupleObjects.cpp
Cuts/include/H_tautau_2016_baseline.h
Cuts/include/H_tautau_2016_sm.h
Cuts/include/H_tautau_2017_baseline.h
Cuts/include/hh_bbtautau_2017.h
McCorrections/test/PileUpCalc_t.cxx
McCorrections/test/TauIdWeight_t.cxx
Production/plugins/TupleProducer_eTau.cc
Production/plugins/TupleProducer_muMu.cc
Production/plugins/TupleProducer_muTau.cc
Production/plugins/TupleProducer_tauTau.cc

Added method AnyAccept with all patterns in TriggerResults class.
Fixed pt muon cut, decayMode and Iso for tau in EventInfoBase class.
Added PassedOldDecayMode method in TupleObject class.
Added Cuts/include/H_tautau_2017_baseline.h
Added SignalObjectSelector class to have different signal selection for different modes.
Moved PassDefaultSelection and GetHiggsCandidateIndex there.
Modified EventInfoBase accordingly, either the different analyzers.

Tau pog v1 data/mc validation

---

Analysis/include/SignalObjectSelector.h
Analysis/src/SignalObjectSelector.cpp

Added a lighter selection for TupleSkimmer to be compatible with HTT QCD estimation

QCD estimation

---

Core/include/TauIdResults.h
Production/interface/BaseTupleProducer.h
Production/python/Production.py
Production/src/BaseTupleProducer.cc
install_framework.sh

Added deepTauv2 and deepFlavour to the recipe. Removed old electronID

Tau and Jet recipes

---

Analysis/include/EventInfo.h
Analysis/include/SignalObjectSelector.h
Analysis/source/GenMatchCheck.cxx
Analysis/src/EventInfo.cpp
Analysis/src/SignalObjectSelector.cpp

Merge taupog branch in prod_v5

Merge taupog in prod_v5

---

Analysis/include/SignalObjectSelector.h
Analysis/src/SignalObjectSelector.cpp
Core/include/EventTuple.h
Core/src/EventTuple.cpp
Instruments/source/TupleMerger.cxx

Fixed code to be compatible with changes in tau_pog_v1

Prod_V5 fixing

---

Production/interface/BaseTupleProducer.h
Production/interface/TriggerTools.h
Production/python/Production.py
Production/src/BaseTupleProducer.cc
Production/src/TriggerTools.cc

Fixed Met Filter recipe and also fixed the possibility to run with the embedded samples

Prod v5 Met Filters

---

Analysis/src/EventCandidate.cpp
Analysis/src/TauUncertainties.cpp

Fixed tau uncertainties, DM 0 correction factor and an error in shifted met

prod v5 tauUnc

---

Analysis/include/EventCacheProvider.h

Added FillEvent method in EventCacheProvider

prod v5 tuple skimmer

---

Analysis/include/EventCacheProvider.h
Analysis/include/EventInfo.h
Analysis/include/SignalObjectSelector.h
Analysis/src/EventCacheProvider.cpp
Analysis/src/EventCandidate.cpp
Analysis/src/EventInfo.cpp
Analysis/src/SignalObjectSelector.cpp
Core/include/CacheTuple.h
Core/include/EventTuple.h
Core/include/TupleObjects.h
Core/src/TupleObjects.cpp
Instruments/test/DummyCacheProducer_t.cxx
JetTools/include/BTagger.h
JetTools/src/BTagger.cpp
McCorrections/src/BTagWeight.cpp
McCorrections/src/EventWeights.cpp

Added the possibility to have a new jet ordering according to the jet_hh_score. Modified cache accordingly

Prod v5 jet score

---

Analysis/src/SignalObjectSelector.cpp
Cuts/include/Btag_2016.h
Cuts/include/Btag_2018.h
JetTools/src/BTagger.cpp

- Update of bTag working points for all the years
- Update of jets ordering for all the years

bjet_eff_ana_v5

---

Analysis/include/TauUncertainties.h
Analysis/src/TauUncertainties.cpp
CMakeLists.txt
McCorrections/include/EventWeights.h
McCorrections/include/LeptonWeights.h
McCorrections/src/EventWeights.cpp
McCorrections/src/LeptonWeights.cpp

- Analysis/include/TauUncertainties.h: Include ES correction for mu->tau
- CMakeLists.txt: add dependence on it for each executable in cmake file
- McCorrections/include/EventWeights.h: Update to new weights 
- McCorrections/include/LeptonWeights: Update to new weights

Updates and implementation of 2018 of the lepton sf

---

Analysis/BuildFile.xml
Production/BuildFile.xml
Production/src/BaseTupleProducer.cc

- Added TauIDSFs and  TauTriggerSFs to build 
- Remove from eventTuple eventEnergyScale

fixed compilation errors 

---

Production/crab/config/2017/TTBar.txt
Production/crab/config/2018/TTBar.txt

- fixed problem with config TTbar 2018

fixed problems last PR

---

Cuts/include/hh_bbtautau_Run2.h

in hh_bbtautau_Run2.h I added the mass window parameters

adding new mass window parameters
